### ISSUE TITLE
Any way to do previous assignments?

### ISSUE THREAD

**Issue by towns** [hapijs/university#156]
I have missed the last two assignments. I can see them in the issues, but is there a way for me to clone the repo in the state it was in for the assignment? Or do I just need to join in on the current assignment?

**Comment by Andersos** [comment]
You can jump back in time with git. Try doing ´git checkout <commit>` of a commit before the assignment merge. 

Should be before assignment 4:
git checkout 6f8774328f87a6dcf8ba606f7247b1c6e580b887 

Should be after 4:
git checkout 0f0abeff1c5053c24344cc6f109913f44a9f5cb0

Should be after 5:
git checkout bddee2bfb6e325fc36726f7e05a3dcfcc81ddc2f

**Comment by zoe-1** [comment]
Created a table of contents / list of assignments. 
Should help people navigate through old assignments. 
[List of Assignments](https://github.com/hapijs/university/blob/master/guides/contents.md)

**Comment by AdriVanHoudt** [comment]
@zoe-1 someone suggested having a branch for each assignment so you can do a PR against that otherwise the PR against master for assignment 1 will look stupid
Also quick reference to all assignments https://github.com/hapijs/university/issues?q=is%3Aissue+is%3Aclosed+label%3Aassignment
And maybe actually link to the commits in the overview (minor stuff)

**Comment by zoe-1** [comment]
@AdriVanHoudt Current situation is a short-term solution.  
In the future, plan to set up the branches like we talked about before. Had several people
asking how to start at earlier assignments so put this up to keep others from getting stuck.

**Comment by AdriVanHoudt** [comment]
:+1:
