### ISSUE TITLE
Deprecate?

### ISSUE THREAD

**Issue by hueniverse** [hapijs/university#267]
Is this still being used? Still active? If not, I'll archive it.

**Comment by zoe-1** [comment]
Hi Eran, 

Active, would like to work on this project and get it up to date.
Have been working on other things like: cryptography.  
Do not want to leave this unfinished as it currently is.
Already developed assignments [for hapi v17](https://github.com/zoe-1/university-rewrite) .
Just need to put some time into it and polish it up :-)

BTW, I got removed from the hapijs org because of two factor auth not being set up on
my account.  Two factor auth is now set up.  Please restore my hapijs org access :-)

hapi extends,
Jon

**Comment by zoe-1** [comment]
OK are alright
cool to use
